### ISSUE TITLE
Small notice from discord may change bot prefix

### ISSUE THREAD

**Issue by Lady-Awinita** [pengowray/sprinto#12]
Discord is starting a bot overhaul command that will strictly enforce use of the slash commands, what they call Privileged Intents. In this case it will enforce the use of /sprint instead of the current prefix of _sprint

I just wanted to let you know this now before the hard requirement begins in April

I am also curious of how many servers Sprinto is in ? Becauese if it is less then 100 servers, its as easy as flipping a switch in the bot controls panel in discord developer mode

**Comment by pengowray** [comment]
I thought I'd try tackling slash commands today for Sprinto, but I was quickly thwarted as I discovered Discord.Net (the iscord library I'm using, which has been largely wonderful) does not yet support them.

> interactions (buttons and slash commands) are not yet supported by Discord.Net, you'll have to wait for the rewrite, use one of the forks [discord.net labs] or another library like Disqord/DSharpPlus

**Comment by Lady-Awinita** [comment]
So I take it there is no way for Sprinto to get privlisged intent approval ?

**Comment by pengowray** [comment]
Yeah, unfortunately not. I'd really have to contrive some kind of excuse. 

Slash commands have been added now for the sprinting functions, but they're still a work in progress overall for the bot.
