### ISSUE TITLE
Slash command requirement for bots coming soon

### ISSUE THREAD

**Issue by Ru-Doragon** [pengowray/sprinto#15]
Was just curious what the status is on Sprinto and slash commands for the bot on Discord. According to a recent post, other commands are going to stop working sooner rather than later and we wouldn't want to loose access to Sprinto's capabilities. :) Thanks for all you do!

https://discord.com/blog/slash-commands-permissions-discord-apps-bots

**Comment by pengowray** [comment]
Hey Ru-Doragon, Looks like I missed this post.

They're working now 😀 Happy sprinting
