### ISSUE TITLE
Suggestion: Add command to amend the words submission

### ISSUE THREAD

**Issue by MrViso** [pengowray/sprinto#18]
I have received feedback on my Discord server that some users want to change their final submission at the end of the sprint based on the initial word count. There were some issues with users using the wrong command or forgetting an operator. As a result, they had to manually calculate a difference before they could report the correct wordcount. This was quite frustrating for them.

Here the use case briefly presented:

```
# User did join the sprint.
/join 500

# Sprint was finished
# User wrote 515 words. 
# User did count only the new words in the documents
# User wanted to add the new words, but forgot the + or add operator

/words 515

# Sprinto only counted the new 15 words
# User wants to amend the submission instead of calculate the differance between the words written and the words submitted before.
# User has to calculate the difference and report it: -> 500 words

/words +500
=> 1015 (515 new words)

# User would rather make a correction based on the initial word count. Maybe like that:
/words init+515 

```
I don't know which kind of operator could explain Sprinto that he should use the initial word count for the calculation instead of the updated one, but maybe there is a good solution :)

**Comment by pengowray** [comment]
Hi, thanks for the suggestion

It might not be well documented, but you can do this with "new", e.g. 

`/words 515 new`

Closing the issue but let me know if you meant something different

**Comment by MrViso** [comment]
Oh thanks! You're right. I didn't see the difference between `+` and `new`. I will share the information to our users.
:)
