### ISSUE TITLE
`_who` is sprinting

### ISSUE THREAD

**Issue by japanoise** [pengowray/sprinto#2]
Should be easy enough, I just want to know who would be sprinting with me when the sprint actually starts.

**Comment by pengowray** [comment]
Hi japanoise,

✅ Added `_who`, as requested. 

Let me know if you notice any issues.

Note, you can also quickly see who's sprinting if your server uses the `@Active Sprinter` role, see: https://github.com/pengowray/sprinto/wiki/ActiveSprinter
