### ISSUE TITLE
/join 2350

### ISSUE THREAD

**Issue by Amethyst-Aries** [pengowray/sprinto#23]
Several years after the war, Hermione moves to America. She wants to get away from the place where everyone knows her and has such high expectations of her. She’s tired, she just wants some time to herself to simply BE. No one asking for her autograph, her photo. No more yearly interviews. She tried to live up to her “Golden Girl” reputation, she really did. She got a job at the ministry where she excelled (of course) but she just felt trapped. It’s exhausting when everyone around you expects you to constantly prove you’re the “brightest witch of the age”. She got tired of it, she wanted out. Out of England, out of Europe all together. She wants a somewhat easy transition and doesn’t want to learn a new language. Australia is out of the question, even the most minute, miniscule chance of running into her parents and not having them recognize her….it hurts her heart too much to even think about. 
 
 
Draco had had enough too, but for entirely different reasons. He couldn’t handle the stares anymore, the whispering. Knowing that most people he encountered didn’t think him worth a damn and certainly didn’t think he deserved to be free. Then there were the nightmares and the panic attacks. The war had left his mental health a wreck. He needed to get away. Somewhere no one knew who he was, where he could start over and maybe, for the first time in his life, be happy. He isn’t sure he even feels he deserves happiness but this constant state of anxiety and self loathing is just too much.A new beginning is the only way he can give himself a fighting chance. He remembers Blaise and his mother fled to the U.S. during the war, they’ve since returned to England and Baise has told Draco how much he enjoyed the U.S. 

2004 
Hermione looked around her London flat, her eyes roaming over her Order of Merlin 1st Class alongside her many other accolades. Her honorary degree from Oxford, she hadn’t even known it had been established by wizards and still offered advanced wizarding academic programs, her medals of honor deeming her a war hero. Photographs from the Prophet, and several awards and certificates from her 4 years working at the Ministry of Magic. She sat on her little sofa, her knees up, holding a mug of earl gray and just stared at this little display of her achievements while her eyes went in and out of focus. She let out a small, almost inaudible sigh and then was abruptly startled out of her stupor as a brilliantly bright stag charged through her window and spoke in Harry’s voice, “I’ll be leaving in 5, you can open your floo.” She smiled at the familiar stag and took her wand out of the high bun resting atop her head to flick it over to the fireplace so that Harry could come through. With her wand no longer holding her hair neatly in place, it cascaded around her shoulders and down her back in a wild mess of curls. She shook her hair out and stood up to stretch. She had been sitting in the same position for over an hour. The tea in her mug had long since turned cold so she went to the kitchen to put the kettle on, since Harry was on his way now too. She paused as she was about to take out a second mug, this conversation was going to call for something a lot stronger than earl gray. She took a bottle of vodka out of her freezer, she never got the appeal of fire whiskey, grabbed two rocks glasses from a cabinet and was walking back into the living room just as the fire turned a bright green.
She watched Harry stumble out of her floo and felt a pang in her heart, even with the vodka this was going to be a hard conversation. As Harry dusted himself off and took off his shoes off, Hermione was touchy about shoes in the house. He looked up and Hermione saw his eyes fall to the liquor bottle in her hands. He raised an eyebrow and said with a little laugh, “Vodka? On a Tuesday? What’s going on?” 
She bit her lip, took a deep breath and motioned to the couch, “Sit down Harry.” 
She walked over and took a seat as he came to sit beside her, the teasing smile falling off his face and being replaced with a look of concern. She opened the bottle and poured them each a glass, throwing hers back before Harry had even picked his up. She gave herself a refill before settling back into the couch, bringing her knees up. 
“Hermione, you’re starting to scare me. Are you alright?”, said Harry, resting a hand on her knee. 
She looked into the green eyes of the best friend she’d ever had, her first real friend and said, “I’ve given in my resignation at the ministry. Today was my last day. I didn’t tell you sooner because I thought you’d have tried to talk me out of it, and frankly you’re probably the only person in the world who’d have been able to.” Harry looked at her with a confused expression, tilting his head to the side and she watched as slowly, the confusion shifted to something she couldn’t quite place. 
He picked up the glass she’d poured for him and took a sip, making a face of disgust before putting it back down on the coffee table, “Well, I know that can’t be the worst of it. You wouldn’t have sent me an owl saying I needed to hurry over as soon as I finished practice, nor would you be drinking straight vodka, if the only thing you had to tell me was you’ve quit your job.” 
Hermione gave him a small smile, thankful that he knew her so well. Though, 12 years of friendship and fighting a war together would tend to create a strong bond. 
“Ok, I’m going to come out with it but I’m going to ask that you don’t interrupt me and let me get it all out before you say a word. You also need to promise to not try to change my mind.” 
He nodded as he went back to his drink. “Good idea”, she said, “you may need that after I’m done.” 
She took a deep breath and started, “I can’t do it anymore Harry. I can’t be Hermione Granger Golden-Girl anymore. I’m so tired of the pressure, the way people have these insanely high standards and expectations for me. I am so sick and tired of having to be perfect all the time. When we were kids I’d have given anything for the life I have now but after all these years, after fighting in a war and then immediately going to work at the Ministry, I haven’t had a moment to sit down and decide if this is even what I want. I feel like after everything I’ve been through, everything WE’VE been through, I need to just stop and breathe.” She took a deep breath and looked at Harry, inwardly pleading he’ll get it. Out of everyone, she needs him to get it. 
He looked at her with a look she can’t quite pinpoint, and she sees him smirk, look down and give a shaky little laugh. A nervous, yet resolute sound. “Well, if anyone can relate to you it’s me, ‘The chosen one who lived’ and all that.”
She’s suddenly horror struck, how could she be this thick? How could she unload this all onto Harry?! Harry, who lived through all of it with her plus 10 times more. “Harry, merlin I’m so sorry! You’ve got to be hating me right now, you deal with so much more than me on a daily basis and here I spilling my guts like a pathet-” He puts a hand up to stop her and smiles, “Hermione, you are probably the last person on the face of this earth that I’d call pathetic. I could never hate you. I’d be lying if I didn’t think similar things all the time, but, I think I’ve just accepted it. It doesn’t bother me much anymore, but that doesn’t mean I don’t understand how it bothers you. You’ve had people expecting the absolute best from you since you were 11 years old and the only one to levitate a feather on the first try. You’ve earned a break.”
She looked to the floor smiling and gives a nervous laugh, swirling the last few drops of the clear liquor in her glass, and then sighed. She wasn’t sure if she felt relieved or guilty, maybe both. 
Harry downed the rest of his drink with a grimace, “gods thats disgusting”. He set it down and suddenly looks more serious, so much older and wiser than any 24 year old should ever look. “So, where are you going?”
Hermione’s head pops up and she bites her lip for a second, “what do you mean?”
“Come off it. As I said before,there is no way you asked me to rush over here and down that foul stuff,” he juts his chin over to the still open vodk bottle on the coffee table, “just to tell me you’ve resigned. You’re moving aren’t you?”
Moments like this truly made her appreciate the bond she and Harry had. She gave a little nod, chewing at her lip again.
“Right then, well where to? Will you stay in Britain?” 
“I’m not even staying in Europe.”
Harry looked surprised momentarily, then nodded in understanding. Then looked slightly uncomfortable, “Australia…?”
“No”, she answered quickly, shaking her head, “I know the likelihood of running into them is so miniscule but even risking it…” she swallowed, “I don’t think my heart could bear seeing them and them not knowing me.” She shook off the momentary sadness and smiled, “I’m going to New York.”
“The U.S? Really?” 
“Yes really, why are you so surprised?” 
Harry laughed, “I just can’t picture you over there that’s all.”
She rolled her eyes, “Oh right, because you’ve been so many times and know what to picture.”
Harry was pouring himself another shot, “No, i’ve only been the once. To meet with the President of MACUSA. It was just after the war, I’d gotten some medal of honor or something. Frankly I wanted to tell her to throw it in the bin, after how they ignored the war it felt like a slap in the face.” he looked down at his glass, “I need something to mix this with Hermione, it really is foul.” 
As he got up to get a fizzy pop he called over his shoulder, “but aside from that I’ve not been so I suppose you’re right.” He settled back on the sofa next to her, pouring the pop in with his liquor and drinking deeply. “Ah, much better. So, golden girl,” she swatted at his shoulder with a throw pillow, “what’s the plan then?”
She leaned over to pour some more vodka into her own glass, adding some pop too now, and said “That’s just it. There’s no plan. I’ve got a good deal of money saved up, and I’ve already gotten an apartment. I’m just going to go over there and see what it’s like to simply, be.” She took a sip and looked up at Harry, smiling slyly, “Besides, if it doesn’t work out I’ll just come back, I am the golden girl afterall, I’d get my job back in two seconds.”
They both laughed, spending the rest of the evening getting sloshed, reminiscing on all the memories they usually tried not to talk about. All the adventures they’d had, the times they were made to behave as adults when merely children. It was well past 2 in the morning when they finally fell asleep.
—---------------------------------------------------------------------------------------------------------------------------
2 WEEKS LATER
Hemione stood in the center of her now empty flat and slowly spun on the spot. 
“Having second thoughts? Because I have no problem un-packing every last one of those bloody boxes!” Ginny was leaning on the door frame, “I’ll complain the whole time but I’ll do it if it means you’re staying.”
Hermione smiled, “no, just saying a little goodbye, to my first adult home.”
“Oh well, wishful thinking.” she walked into the flat and the two girls hugged.
“Alright ladies, enough tears, we need to get you going Hermione or you’ll miss your flight!”
They pulled apart and Ginny scoffed. “We weren’t crying Potter, need i remind you that you’re the one who was a blubbering mess at the pub the other night for her going away party?”
He cleared his throat and mumbled something about “...just grab this last box then…”
Ginny turned to look at Hermione, “Why are you taking an airplane anyway? Surly a portkey would be faster?”
“Nostalgia I suppose. I’d always fly with my parents if we left the country. Besides, I actually really enjoy flying.”
A short while later they apparated to Heathrow airport, all of Hermione’s possessions magically shrunk and stuffed into a duffle bag with  an undetectable extension charm on it. She turned to Harry and Ginny, “Oh please don’t cry Harry!” said Hermione as Ginny scoffed and said under her breath, “crybaby.”
“I’m just really going to miss you.” 
She walked over to him and threw her arms around him, “I’m going to miss you too! More than I can say, you’re my best friend in the world.” She could feel the tears starting to prick her own eyes and when she gave a little sniffle she heard Ginny clear her throat, “ok ok let’s get this show on the road. Potter, clean yourself up!” Hermione laughed and went to hug Ginny, “take care of him Gin, and take care of yourself. I’m going to miss you so much!” As she backed away she saw Ginny wipe away a tear and say “oh shut up!”
She hugged them each one more time before tuning into the airport.
—----------------------------------------------------------------------------------------------------------------------------
3 YEARS LATER
Hermione woke in her small NYC apartment, the sun shining through her tiny window. She stretched and waved her wand in the direction of her kitchen, starting a pot of hot water to brew her earl grey. She brushed her golden brown curls out of her face and sluggishly got out of her bed. Making her way over to the bathroom to shower she passed closet that she passed everyday and rarely opened. She paused for just a moment before shaking her head and continuing to get ready for the day. 

After washing up and getting dressed for the day, Hermione sat at her kitchen table sipping her tea and sketching in an almost full up book. Never one for a big breakfast, a triangle of toast with a night taken out kf it sat in front of her. 

In the three years since she left England Hermione had started to become the witch she had wanted to be for so long. Without expectations and duties bogging her down she felt free to explore her creative side and to even begin using her once rare hobby of drawing to make a decent living. 

Once she was finished with her tea and added the last finishing touches on the sheyck she was working on, she gathered her things together and headed out the door. Adding her protective wards and enchantments with a flourish of her wand as she walked down the hall. 

It was a beautiful spring day in her little neighborhood. Hermione adored it here and each passing day confirmed more and more that she made the right decision 
Upon arriving to New York, Hermione quickly discovered that the West Village was primarily a wizarding safe haven hidden in plain sight. There were several Crystal shoppes abs apothecaries that any muggle would take for novelty, but we're owned by actual witches or wizards. The gem of the village was a hidden street, similar to that of diagon alley. Though Hermione's British roots wouldn't let her admit it was slightly more fantastic. After popping into her favorite cafe flr her second yea kf the day, Hermione rounded the corner of Canal street and headed down a subway entrance. Instead of continuing down to the platform however, she inconspicuously took out her want abs tapped the letter Z in a graffiti mural. 

The wall shivered slightly before becoming strangely opaque, like a very dirty and old window. She stepped through and a second later it was back to being just a regular wall in a regular subway station.

Hermione couldn't help but smile as she entered into Zarrow Court, aside from the NY library, this had been her absolute favorite discovery since moving across the pond.

**Comment by RFonzi** [comment]
+1

**Comment by pengowray** [comment]
I'm just going to say thank you for the very detailed feedback, and sorry I was unable to replicate the issue.
