### ISSUE TITLE
Automatically add the sprint starter to the sprint

### ISSUE THREAD

**Issue by ellenhutchings** [pengowray/sprinto#4]
It would be really good to add the person who starts the sprint with the equivalent of a `_join same` or even an optional third parameter, `_sprint length delay joinWordCount`.

Often when running a lot of sprints, the starting person can forget to add, and then the start notification means they have to hurry to try and add.

**Comment by pengowray** [comment]
Sprinto will still ping you at the start and end of Sprints even if you haven't joined. There was a bug recently that stopped these pings and it caused some confusion, and I'm sorry about that. But it's been fixed now.

From the FAQ:

> Why do I need to join my own sprint? Shouldn't I join automatically?

>    1. Sprinto doesn't know your starting word count, and doesn't want to guess.

>    2. So other people in the channel can easily follow your lead and join too without having to look up documentation on how to do it.

>    3. You'll get pinged anyway. Sprinto warns you at the start and end of sprints, in case you forgot to join your own sprint.

I've thought about allowing you to add a starting word count when creating a sprint but I worry it would just make the sprinting process look too confusing to other potential sprinters. So sorry for the extra step, but you can always immediately `_join` after starting a sprint.

**Comment by ellenhutchings** [comment]
When the sprint ends it can be a bit of a time crunch to try and join and do the ending word count. Maybe the creator could be pinged within a minute of the start in case the cascade of join messages means they didn't realise they forgot?
