### ISSUE TITLE
Sprinto not responding

### ISSUE THREAD

**Issue by OriginTC** [pengowray/sprinto#9]
Was running sprints with my writing server, and the Sprinto bot went offline. I can't find any updates scheduled for the bot, and I want to confirm that the bot hasn't been pulled.

**Comment by pengowray** [comment]
Hey, sorry I missed your message. 

Sorry! Yes, Sprinto was down, as were many bots. There wasn't a huge amount of communication from Discord about what happened and why.

Message from Discord:

> Hey all. Known issue going on right now with sharding errors when starting your bots. It's been escalated and we're looking into it.

It's hard to get messages out about Sprinto's status, but for next time you can subscribe to/follow Sprinto's status channel to get updates sent to your Discord server.

Invite link:

https://discord.gg/GYXYqFa
